[package]
name = "lcr"
version = "0.1.0"
authors = ["Jack Spira <jjspira@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
log = "0.4.8"
pretty_env_logger = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
failure = "0.1.6"